import { useState } from 'react'
import kalsarpImage from '../images/kalsarp.png'
import kumbhVivahImage from '../images/kumbhvivah.png'
import kushavartaImage from '../images/kushavartakund.png'
import mahaMrityunjayImage from '../images/mahamrutunjay.png'
import narayanNgbaliImage from '../images/narayannagbali.png'
import rahuKetuImage from '../images/rahuketu.png'
import rudraAbhishekImage from '../images/rudraabhishek.png'
import trambakMandirImage from '../images/trambakmandir.png'
import tripindiImage from '../images/tripandi.png'

const phone = '+916268922713'
const phoneDisplay = '+91 62689 22713'
const whatsapp = '916268922713'
const imageAssets = { kalsarp: kalsarpImage, narayan: narayanNgbaliImage, tripindi: tripindiImage, rudra: rudraAbhishekImage, kumbh: kumbhVivahImage, maha: mahaMrityunjayImage }
const pujas = [
  ['Kaal Sarp Dosh Nivaran Puja', 'A time-tested spiritual remedy performed to counteract Rahu and Ketu inclinations and restore balance.', '3–4 Hours', 'Silver Naag Pujan', 'kalsarp'],
  ['Narayan Nagbali Puja', 'Conducted exclusively at Trimbakeshwar to liberate unsatisfied ancestral souls through a complete three-day vidhi.', '3 Consecutive Days', 'Complete Havan', 'narayan'],
  ['Tripindi Shradh Puja', 'Sacred rite for souls who passed away young or whose regular yearly shradh ceremonies were missed.', '2 Hours', 'Pind Daan Samagri', 'tripindi'],
  ['Rudra Abhishek Puja', 'Lord Trimbakeshwar is bathed ceremoniously with sacred panchamrit, sugarcane juice and holy Godavari jal.', '1.5–2 Hours', '108 Bilva Patra', 'rudra'],
  ['Kumbh Vivah Puja', 'Ancient Vedic symbolic ceremony for counteracting intense Mangal Dosh affecting prospective marriages.', '2 Hours', 'Earthen Pot Rites', 'kumbh'],
  ['Maha Mrityunjay Mantra Jaap', 'Chanting of the 32-word supreme healing mantra using genuine Rudraksha malas in Kusha asan.', '11,000 to 1.25L Jaap', 'Rudraksha Beads', 'maha'],
]
const perks = [['✺', 'Authorized Sansthan Pandit', 'Registered and certified Acharya at Trimbakeshwar Jyotirlinga with verified family lineage.'], ['▤', 'Strictly As Per Shashtra', 'Every mantra and vidhi is executed according to original Vedic texts with exact pronunciation.'], ['♙', 'Separate Individual Vidhi', 'No mass crowd batches. Your family receives an individual hawan kund and focused attention.'], ['♟', 'Multiple Vedic Pandits', 'For complex pujas, a synchronized team of scholars assists the primary Acharya.'], ['✧', 'Free Kundali Verification', 'Share your birth details over WhatsApp or phone call prior to travel.'], ['⌂', '24×7 Yatri Hospitality', 'Complete assistance with clean dharamshala accommodation and temple entry coordination.']]
const reviews = [['“Best pandit in Trimbakeshwar. Highly recommended. Panditji explained each step of our Kalsarp Puja patiently and made all arrangements near Kushavarta Kund seamless.”', 'Amar Saxena', 'Mumbai, Maharashtra'], ['“I must say please do perform your puja rituals by Pandit Krishna Guruji. Our family completed Narayan Nagbali over 3 days.”', 'Prachi Kumari', 'Panaji, Goa'], ['“Panditji is having very good knowledge of all puja vidhis. They are very knowledgeable and guided us with deep precision.”', 'Priyansh Kapoor', 'Ujjain, Madhya Pradesh']]
const faqs = [['How to remove Kaal Sarp Dosh permanently?', 'The suitable remedy depends on your kundali. Speak to Guruji for personal guidance before booking.'], ['How can I check if I have Kaal Sarp or Pitru Dosh in my Kundali?', 'Share your birth details for a free initial kundali consultation.'], ['How many types of Kaal Sarp Dosh are there?', 'There are twelve traditional types, each interpreted according to the chart.'], ['Can I perform the Narayan Nagbali puja on my own?', 'This detailed ritual is traditionally performed under an experienced authorised pandit.'], ['Are the puja dakshina charges transparent and affordable?', 'Yes. We explain the recommended vidhi and arrangements clearly before confirming.'], ['What is the dress code required during puja rituals?', 'Traditional, modest clothing is advised. We will share exact preparation details.'], ['Is photography allowed inside Trimbakeshwar Temple?', 'Photography is not permitted in the sanctum sanctorum.'], ['How to conveniently reach Trimbakeshwar from Mumbai or Pune?', 'Trimbakeshwar is reachable by road from Nashik. We can guide you on arrival planning.']]

function Brand() { return <a className="brand" href="#home"><span className="brand-seal">ॐ</span><span>Trimbakeshwar<small>POOJA VIDHI SANSTHAN</small></span></a> }
function WhatsAppButton({ children = 'Consult Guruji', className = '', href = '#booking' }) { return <a href={href} className={`orange-button ${className}`}>✆ <span>{children}</span></a> }
function SocialIcon({ type }) { const paths = { whatsapp: 'M12 2a10 10 0 0 0-8.65 15l-1.1 4 4.1-1.08A10 10 0 1 0 12 2Zm5.82 14.2c-.25.7-1.43 1.27-1.97 1.35-.5.08-1.13.12-1.82-.1-.42-.14-.96-.32-1.66-.62-2.92-1.26-4.83-4.2-4.98-4.4-.15-.2-1.2-1.6-1.2-3.05 0-1.45.76-2.16 1.03-2.46.27-.3.59-.37.79-.37h.56c.18 0 .42-.07.66.51.25.6.84 2.04.91 2.19.08.15.13.33.02.54-.1.21-.16.33-.31.5-.15.18-.32.39-.45.52-.15.15-.3.32-.13.62.17.3.75 1.23 1.6 2 1.1.98 2.02 1.28 2.32 1.43.3.15.48.13.66-.08.18-.21.76-.89.96-1.2.2-.3.4-.25.67-.15.28.1 1.75.83 2.05.98.3.15.5.23.57.36.08.13.08.76-.17 1.46Z', instagram: 'M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7Zm5 3a5 5 0 1 1 0 10 5 5 0 0 1 0-10Zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm5.25-3.5a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5Z', facebook: 'M13.5 21v-8h2.75l.41-3h-3.16V8.08c0-.87.25-1.46 1.5-1.46h1.6V3.94c-.28-.04-1.22-.12-2.32-.12-2.3 0-3.87 1.4-3.87 3.98V10H8v3h2.41v8h3.09Z' }; return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[type]} /></svg> }

export default function App() {
  const [menu, setMenu] = useState(false), [service, setService] = useState(''), [message, setMessage] = useState('')
  const goToBooking = (name) => { setService(name); document.querySelector('#booking')?.scrollIntoView({ behavior: 'smooth' }) }
  const submit = (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const text = `*New Consultation Request*%0A%0A*Name:* ${encodeURIComponent(data.name)}%0A*Phone:* ${encodeURIComponent(data.phone)}%0A*Pooja:* ${encodeURIComponent(data.service || 'Not sure yet')}%0A%0ASent from the Trimbakeshwar Pooja Vidhi website.`; window.open(`https://wa.me/${whatsapp}?text=${text}`, '_blank', 'noopener,noreferrer'); setMessage('WhatsApp has opened with your details ready to send to Guruji.'); event.currentTarget.reset(); setService('') }
  return <><div className="topbar"><span>✺ AUTHORISED TRIMBAKESHWAR JYOTIRLINGA POOJA SERVICES</span><i /> <span>24×7 Free Kundali & Muhurat Consultation</span><a href={`tel:${phone}`}>✆ Pandit Krishna Guruji: {phoneDisplay}</a></div>
    <header><Brand /><button className="menu" onClick={() => setMenu(!menu)} aria-label="Menu">☰</button><nav className={menu ? 'nav open' : 'nav'}>{[['#services', 'Puja Services'], ['#about', 'About Guruji'], ['#muhurat', 'Muhurat & Dates'], ['#temple', 'Temple Guide'], ['#pilgrimage', 'Pilgrimage & Kumbh Mela'], ['#guidance', 'Blog'], ['#faq', 'Contact']].map(([to, label]) => <a href={to} key={label} onClick={() => setMenu(false)}>{label}</a>)}<WhatsAppButton /></nav></header>
    <div className="assurance"><span>◉ 45+ Years Vedic Heritage</span><span>♨ Authorized Sansthan Pandit</span><span>♧ 24×7 Free Kundali Consultation</span><span>♟ 100% Individual Vidhi (No Batch Merging)</span><a href={`tel:${phone}`}>✆ {phoneDisplay}</a></div>
    <main><section className="hero" id="home"><div><p className="kicker">◉ KUSHAWART TEERTH JYOTIRLINGA PARAMPARA</p><h1>Trimbakeshwar Pooja Vidhi: <em>Sacred Vedic Pujas</em> As Per Shastra</h1><p className="intro">Authentic, personal rituals performed at Trimbakeshwar Jyotirlinga — Kaalsarp Dosh Nivaran, Narayan Nagbali, Tripindi Shradh, and Rudra Abhishek by certified scholar <b>Pandit Krishna Guruji.</b></p><div className="chips"><span>▣ Authorised Pandit</span><span>◫ Free Kundali Check</span><span>✣ Separate Individual Vidhi</span><span>▣ 24×7 Muhurat Help</span></div><div className="hero-actions"><WhatsAppButton href={`tel:${phone}`}>Call Guruji: {phoneDisplay}</WhatsAppButton><a className="outline-button" href="#services">▤ Explore All 7 Pujas</a></div><div className="stats"><span><b>45+ Yrs</b>Vedic Experience</span><span><b>100%</b>Individual Vidhi (Free)</span><span><b>24×7</b>365 दिन उपलब्धता</span></div></div><div className="hero-photo"><img src={trambakMandirImage} alt="Trimbakeshwar temple" /><small>Historic Peshwa Baji Rao Architecture</small><div className="floating-proof"><b>◉ &nbsp; Certified Sansthan Vidhi</b><span>Every ritual performed individually with authentic Vedic mantras & certified samagri.</span></div></div></section>
      <section className="about section" id="about"><div className="about-photo"><img src={kushavartaImage} alt="Kushavarta Kund at Trimbakeshwar" /><div><small>PURE TRADITION</small><b>Pandit Krishna Guruji</b><span>Authorised Senior Acharya, Kushawart Ghat, Trimbakeshwar</span></div></div><div><p className="kicker">◉ ABOUT THE REVERED ACHARYA</p><h2>Trimbakeshwar Pujari <em>Pandit Krishna Guruji</em></h2><p>Pandit Krishna Guruji carries over <b>25 years of unbroken Vedic tradition</b> at Trimbakeshwar Jyotirlinga. Recognized as one of the most respected authorities for Kaalsarp Dosh, Narayan Nagbali, and Tripindi rituals, he adheres strictly to authentic Shastric Samhitas.</p><p>Devotees across India and overseas consult Guruji for accurate horoscopic readings. Rather than rushed collective rituals, Guruji ensures separate individual setups with pure hawan samagri, clear guidance, and compassionate devotee care.</p><div className="mini-perks">{perks.slice(0, 6).map(([icon, title, text]) => <article key={title}><i>{icon}</i><b>{title}</b><small>{text.split('. ')[0]}</small></article>)}</div><div className="online"><WhatsAppButton className="speak-guruji" href={`tel:${phone}`}>Speak with Guruji Directly</WhatsAppButton><span>● Guruji is available on call right now</span></div></div></section>
      <section className="services section" id="services"><p className="kicker">VEDIC RITUALS & ANUSHTHANS</p><h2>Sanctified Puja Vidhis at Trimbakeshwar</h2><p className="section-sub">Each ritual is scheduled on Shastric muhurats, accompanied by full samagri, Kushavarta holy bath rites, and personal sankalp.</p><div className="puja-grid">{pujas.map(([name, detail, duration, extra, image]) => <article className="puja-card" key={name}><div className="card-image" style={{ backgroundImage: `url(${imageAssets[image]})` }}><span>{image === 'narayan' ? '3-DAY EXTENSIVE VIDHI' : 'SAME-DAY VIDHI'}</span></div><div className="card-copy"><h3>{name}</h3><p>{detail}</p><div className="tags"><span>⌛ {duration}</span><span>✦ {extra}</span><span>♦ Kushavarta Snan</span></div><button onClick={() => goToBooking(name)}>✆ Book {name.replace(' Pooja', '')}</button></div></article>)}</div><article className="featured-puja"><div className="rahu-image" style={{ backgroundImage: `url(${rahuKetuImage})` }} /><div><p className="kicker">RAPID 45-MINUTE RITUAL</p><h3>Rahu Ketu Dosh Nivaran Pooja</h3><p>Targeted planetary ceremony neutralizing negative shadow afflictions that cause career roadblocks, sudden loss, and chronic legal hurdles.</p><div className="tags"><span>⌛ 45 Minutes Vidhi</span><span>✦ Navgraha Peeth</span><span>♦ Economical Dakshina</span></div></div><button onClick={() => goToBooking('Rahu Ketu Dosh Nivaran Pooja')}>✆ Book Rahu Ketu Puja</button></article></section>
      <section className="section why"><p className="kicker">VEDIC AUTHENTICITY</p><h2>Why Perform Puja With Pandit Krishna Guruji?</h2><p className="section-sub">Integrity, accurate Shastric compliance, and deep devotee reverence set Panditji’s rituals apart from rushed tourist setups.</p><div className="why-grid">{perks.map(([icon, title, text]) => <article key={title}><i>{icon}</i><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="life-section"><div className="life-heading"><div><p className="kicker">TAILORED SPIRITUAL SOLUTIONS</p><h2>Recommended Pujas by Life Situation</h2></div><p>Not sure which ritual your horoscope requires? Match your current life challenge to the corresponding Vedic shanti vidhi.</p></div><div className="life-grid">{[['▣','Career & Financial Delays','Unexplained business stalls, sudden monetary loss, repeated interview failures.','Kaal Sarp / Rahu Ketu Shanti'],['☁','Ancestral Peace & Pitru Dosh','Repeated family disputes, lack of children, strange dreams and departed ancestors.','Narayan Nagbali / Tripindi'],['◉','Marital Delay & Discord','Extreme delays in finding marriage, broken alliances, severe Mangal dosh affliction.','Kumbh Vivah / Ark Vivah'],['♧','Health Protection & Longevity','Chronic unexplained disease, fear of accidents, negative black aura.','Maha Mrityunjaya & Rudra Abhishek']].map(([i,t,d,r]) => <article key={t}><i>{i}</i><h3>{t}</h3><p>{d}</p><small>Recommended Vidhi:</small><b>{r}</b><button onClick={() => goToBooking(r)}>Consult for {t.split(' ')[0]} →</button></article>)}</div></section>
      <section className="muhurat section" id="muhurat"><div><p className="kicker">AUSPICIOUS TITHIS & CALENDAR</p><h2>Choosing The Right Shubh Muhurat</h2><p>In Vedic astrology, muhurat governs the cosmic vibration received by the Yajman. While Trimbakeshwar has continuous divine presence, certain tithis amplify the power many times over.</p>{[['☼','Shukla Paksha (Waxing Phase)','Ideal for Purnima Vrat, Satyanarayan Puja, and prosperity abhisheks.'],['☾','Amavasya & Pitru Paksha','Supreme time for Narayan Nagbali, Pitru Tarpan, and Tripindi Shradh.'],['▣','Mahashivratri & Shravan Maas','Peak spiritual windows for Laghu Rudra & Maha Mrityunjaya Jaap.']].map(([i,t,d]) => <article className="tithi" key={t}><i>{i}</i><b>{t}</b><small>{d}</small></article>)}</div><div className="windows"><h3>▣ Upcoming Muhurat Windows <small>SLOTS OPEN</small></h3>{[['Kaalsarp Shanti Dates','Every Amavasya, Panchami, & Designated Mondays (Upcoming: 14th, 21st, 28th)'],['Narayan Nagbali Muhurats','Special 3-day puja windows this month (Upcoming: 14th, 19th, 23rd)'],['Tripindi Shradh Tithis','Krishna Paksha Ashtami & Amavasya days (Upcoming: 13th, 21st, 28th)']].map(([t,d]) => <div key={t}><b>{t}</b><span>{d}</span><button onClick={() => goToBooking(t)}>Reserve Date</button></div>)}<p>Need personalized date check as per your Janma Nakshatra? <a href="#booking">Ask Guruji →</a></p></div></section>
      <section className="temple section" id="temple"><p className="kicker">SACRED GEOGRAPHY & DARSHAN</p><h2>The Holy Kushavarta Kund & Jyotirlinga Dham</h2><p className="section-sub">Trimbakeshwar is unique among the 12 Jyotirlingas: the Lingam has three faces embodying Brahma, Vishnu, and Maheshwar.</p><div className="temple-grid"><div className="kund-photo"><img src={kushavartaImage} alt="Kushavarta Kund" /><span><b>KUSHAWARTA TEERTH</b>Devotees take the ritual holy bath before entering the sanctum for puja vidhi.</span></div><div className="temple-tips">{[['♙','Temple Dress Code','Traditional attire is strictly advised. For special Abhishek and Nagbali pujas, men must wear a dhoti and women must wear a Saree.'],['◷','Best Darshan Timings','Early morning hours (5:30 AM - 9:00 AM) are peaceful and optimal for darshan.'],['▧','Sanctum Photography','Photography inside the core sanctum sanctorum is prohibited by Sansthan regulations.'],['▰','How to Reach','Located 28 km from Nashik Railway Station. Frequent buses, private cabs, and shared jeeps operate.']].map(([i,t,d]) => <article key={t}><i>{i}</i><b>{t}</b><p>{d}</p></article>)}<div className="nearby"><b>NEARBY PILGRIMAGE CIRCUIT</b><p>Extend your sacred journey to neighboring revered teerth locations:</p><span>Aundha Nagnath</span><span>Grishneshwar Jyotirlinga</span><span>Bhimashankar</span><span>Shiv Jata Mandir</span></div></div></div><div className="kumbh" id="pilgrimage"><div><small>GRAND CONGREGATION 2026–2027</small><h2>Trimbakeshwar–Nashik Simhastha Kumbh Mela</h2><p>Occurring once in 12 celestial cycles when Jupiter enters Leo, millions of sadhus, akharas, and pilgrims gather for the divine Shahi Snan.</p></div><WhatsAppButton>Kumbh Pre-Registration</WhatsAppButton></div></section>
      <section className="testimonials section" id="guidance"><p className="kicker">DEVOTEE REVERENCE</p><h2>What Yajmans Say About Guruji</h2><p className="section-sub">Over two decades of heartfelt gratitude from pilgrims who traveled to Trimbakeshwar seeking peace and karmic release.</p><div className="testimonial-grid">{reviews.map(([quote,name,city]) => <article key={name}><i>★★★★★</i><p>{quote}</p><div><b>{name}</b><small>{city}</small></div></article>)}</div><div className="guidance"><p className="kicker">POOJA GYAN & ASTROLOGICAL ARTICLES</p><h2>Vedic Guidance & Insights</h2><div>{[['काल सर्प पूजा के फायदे (Kalsarp Pooja Benefits)','क्या लगातार कोशिशों के बावजूद आपको बार-बार एक जैसी चुनौतियों का सामना करना पड़ता है?'],['Pitra Dosh Nivaran Puja In Trimbakeshwar','Many individuals encounter unforeseen issues in life without knowing the true cause.'],['Trimbakeshwar Temple Kaal Sarp Puja & Remedies','Maharashtra’s Trimbakeshwar Temple is the premier tirth for carrying on remedies.']].map(([t,d]) => <article key={t}><small>ज्ञान व धर्म लाभ</small><h3>{t}</h3><p>{d}</p><a href="#booking">Read Detailed Guide →</a></article>)}</div></div></section>
      <section className="faq section" id="faq"><p className="kicker">DEVOTEE CLARITY</p><h2>Frequently Asked Questions</h2><p className="section-sub">Transparent answers to all practical and ritual questions regarding your visit to Trimbakeshwar.</p><div>{faqs.map(([q,a],i) => <details key={q}><summary>{i + 1}. {q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
      <section className="booking" id="booking"><div><p className="kicker">BEGIN YOUR SACRED VISIT</p><h2>Speak with Guruji personally.</h2><p>Share your details and WhatsApp will open with your consultation request ready to send.</p></div><form onSubmit={submit}><label>Your name<input name="name" required placeholder="Enter your name" /></label><label>Phone number<input name="phone" required type="tel" placeholder="Enter phone number" /></label><label>Which pooja are you interested in?<select name="service" value={service} onChange={(e) => setService(e.target.value)}><option value="">Select a pooja</option>{pujas.map(([n]) => <option key={n}>{n}</option>)}<option>Other / not sure yet</option></select></label><button>Send request on WhatsApp ↗</button><p aria-live="polite">{message}</p></form></section></main>
    <footer><div className="footer-call"><div><b>Planning Your Pilgrimage to Trimbakeshwar?</b><span>Connect with Pandit Krishna Guruji for free Kundali diagnosis, tithi guidance & guest house help.</span></div><WhatsAppButton href={`tel:${phone}`}>{phoneDisplay} (24×7 Available)</WhatsAppButton></div><div className="footer-grid"><div><Brand /><p>Authentic Vedic rituals performed strictly according to Shastras by Pandit Krishna Guruji — senior scholar carrying over 45+ years of pure parampara at Kushavart Teerth, Trimbakeshwar Jyotirlinga.</p><div className="social-links"><a href={`https://wa.me/${whatsapp}`} aria-label="WhatsApp"><SocialIcon type="whatsapp" /></a><a href="https://instagram.com/trimbakeshwarpoojavidhi" target="_blank" rel="noreferrer" aria-label="Instagram"><SocialIcon type="instagram" /></a><a href="https://facebook.com/trimbakeshwarpoojavidhi" target="_blank" rel="noreferrer" aria-label="Facebook"><SocialIcon type="facebook" /></a></div></div><div><b>PAVITRA PUJAS</b><a href="#services">Kaalsarp Shanti Puja</a><a href="#services">Narayan Nagbali Vidhi</a><a href="#services">Tripindi Shradh Puja</a><a href="#services">Maha Mrityunjaya Jaap</a></div><div><b>PILGRIMAGE GUIDANCE</b><a href="#temple">Temple Darshan Timings</a><a href="#muhurat">Shubh Muhurat Calendar</a><a href="#pilgrimage">Kumbh Mela & Ghat Snan</a><a href="#faq">Vrat & Dress Code Rules</a></div><div><b>SANCTUM OFFICE</b><p>⌾ Near Kushawart Tirtha Ghat, Trimbakeshwar, Nashik, Maharashtra 422212</p><a href={`tel:${phone}`}>✆ {phoneDisplay} (24/7 Assist)</a><a href="mailto:info@trimbakeshwarpoojavidhi.com">✉ info@trimbakeshwarpoojavidhi.com</a></div></div><small>© 2026 Trimbakeshwar Pooja Vidhi Sansthan. All sacred rituals performed under Vedic jurisdiction.</small></footer><a className="whatsapp-float" href={`https://wa.me/${whatsapp}`} aria-label="Chat with Guruji on WhatsApp"><SocialIcon type="whatsapp" /></a></>
}
